### ISSUE TITLE
For a plain ascii license

### ISSUE THREAD

**Issue by tst2005** [pygy/The-Romantic-WTF-Public-License#1]
Hello,

Prepare yourself for a uncommon request !

I made lot of stuff around embedding, one of them is to build a "all-in-one" lua file module that contains all his modules parts.
I think you understand the need, you also did it for [lulpeg](https://github.com/pygy/LuLPeg/blob/master/lulpeg.lua)

I start some more complex approach like encoding, compressing, integrity check, etc.
Most of my tries show me lua modules are mainly in plain ascii.

the current version of The-Romantic-WTF-Public-License contains just one character that is not ascii.

- I wonder if it is possible to replace this non-ascii char by something visualy near ?

See my https://github.com/pygy/The-Romantic-WTF-Public-License/pull/2

You probably know that the lua utf8 support lua is quiet recent and can be a long painfull road.

If I can avoid to support utf8 just because of the license content, it will be a gain of time !

I know I will meet non-ascii soon, (probably in author's name)
in all case, I think the license without utf8 can be a good thing.

Best Regards,

**Comment by pygy** [comment]
See my response in #2

**Comment by tst2005** [comment]
Hello,
You refused my request. I understand and accept your choice.
Have lovely fun!

**Comment by pygy** [comment]
Hi,

I prefer to keep the canonical version as is, but I'm ok with changing specific instances that you want to embed. You can also change the license for your own projects.

**Comment by tst2005** [comment]
In fact I think I was too naive.
Even if my tests shown me lot of plain-ascii code, we will probably get more and more code in UTF8.
For example, I can not ask author to change is name to a plain-ascii version ;-)
Well, I need to deal with that and find another way.

For now, I think about
1) minify the code and drop all comment (that is usually the place where non plain ascii comes from)
or
2) just support UTF8 with UTF8 validation
